### ISSUE TITLE
Stuck in Loading

### ISSUE THREAD

**Issue by mrneilix** [SamLewis0602/MMM-Traffic#25]
I'm sure this is a really dumb issue i'm having, but I'm having the issue where it's stuck loading. I tried out the link mentioned in #10 , which worked. When I look at the API dashboard it is not showing any requests from the MagicMirror. Is there any text I need to include prior to the API key in the quotes?

**Comment by mrneilix** [comment]
I found out the issue, I changed the port and it worked fine. Thanks for the great code!

**Comment by SamLewis0602** [comment]
Glad you were able to figure it out! Enjoy the module!

**Comment by mrneilix** [comment]
Thanks for the great work! I love this addition! Out of curiosity, do you know of a way it can display the directions list? The summary only shows 1 street name, but google maps on the computer/phone show quite a few possibilities using each of those streets.

**Comment by SamLewis0602** [comment]
The route summary comes directly from the API, and it only describes the route that is chosen by default. When you use the app, for example, you can choose from multiple routes that have different criteria (fastest, shortest distance, avoids highways, etc.). It seems that the API defaults to choosing the fastest route and only returns the summary for that route. 

As far as listing out the directions list, it's been a while since I looked closely at the API response but I believe it returns each of the "events" for that route, aka the things that would be read aloud by the app when navigating (turns, continue straight, etc.). So in theory, a new config option could be created to list those underneath the current module, I just don't have the time to get it coded :P if you've got the experience and would like to look into it, feel free to submit a pull request!
