### ISSUE TITLE
Dynamic destination

### ISSUE THREAD

**Issue by iRazoR** [SamLewis0602/MMM-Traffic#35]
Hi,

would it be possible to set "Destination" as a dynamic value? I´m storing the parking position of my car in my smarthome system and I would like to use this position as a destination. As the coordinates change daily the destination Value in MagicMirror Config file must be dynamically. Any Idea how I could achieve this?

PS: The access to my Smart Home System (FHEM) will probably be over HTTP

**Comment by SamLewis0602** [comment]
Since the destination is currently read from the config when the mirror launches, this would not be possible from within the magic mirror project. The only way I can see this being possible would be to write a script that runs daily on the pi (could use cron to schedule it) that will edit your config file to change the value for destination and then relaunch the magic mirror project. 

Best of luck. I'm going to close this issue since it doesn't pertain to the module's code itself.
