### ISSUE TITLE
Inconsisent translation

### ISSUE THREAD

**Issue by lolobyte** [SamLewis0602/MMM-Traffic#40]
Please make the entry's like arrival, via, to arrive by an maybe others translatable.

I do this every time by my self but when i do update your Module my translation in your  MMM-Traffic.js are gone. :-(

Please update this.

**Comment by SamLewis0602** [comment]
Unfortunately this would take some time to find a translation library since that part of the module doesn't come from the Google Maps API. Plus then you'd be relying on the library to correctly translate the phrase, but that may be good enough. I don't have the time to do it right now but I will leave the issue up and tag it as an enhancement in case anyone wants to tackle it.

**Comment by bleusswissbless** [comment]
First of all, thx SamLewis0602 for the good job ;)
same problem than lolobyte. hope you will update the module this way :)

**Comment by SamLewis0602** [comment]
I'm sorry all, I misspoke in my previous comment. I will add these options to the config so that you can put your translations there and they will be saved even after updating the module. I will do this work tonight.

**Comment by bleusswissbless** [comment]
Great news !! :)
thank you for your work

**Comment by SamLewis0602** [comment]
The changes have been made and pushed. Please run a `git pull` in the MMM-Traffic folder to get the latest version and then check out the `arriveByText`, `summaryText`, and `leaveByText` options in the config to set your translation. Thanks for the suggestion!
