### ISSUE TITLE
not getting it to work

### ISSUE THREAD

**Issue by Binog** [SamLewis0602/MMM-Traffic#44]
Hey, I only see "Start at: --  Work via -- to arrive at 8:00

`    		module: 'MMM-Traffic',
   			position: 'top_left',
    		classes: 'dimmed medium', //optional, default is 'bright medium', only applies to commute info not route_name
    		config: {
        		api_key: 'my api !?',
        		mode: 'driving',
        		origin: 'start adress',
        		destination: 'end address',
        		arrival_time: '0800', //optional, but needs to be in 24 hour time if used.
        		route_name: 'Work',
        		changeColor: true,
        		showGreen: false,
        		limitYellow: 5, //Greater than 5% of journey time due to traffic
    		    limitRed: 20, //Greater than 20% of journey time due to traffic
    		    traffic_model: 'pessimistic',
    		    interval: 120000, //2 minutes
    		    showWeekend: false,
 		   		allTime: false,
 		   		loadingText: 'Check..',
 		   		prependText: 'Work ',
 		        leaveByText: 'Start at: ',
 		   		hideOffHours: false,
`

I do have two questions:
Since I am in Europe, does it matter HOW the address is inserted? "Street 1, zip code, city"      or " Street+1,Zipcode,city" or somehow else?? 

Can someone please explain how to obtain a api_key. Since I am not sure, fi I have the right one, or if I have done it correctly!?

Thank You !

**Comment by SamLewis0602** [comment]
Hi Binog. 
First, since this module uses the Google Maps API, you can enter your address in the config however you would normally type it into Google Maps. It is pretty forgiving with formatting. You also don't need to worry about encoding special characters or spaces, that will be handled by the module.
Second, the dashes are appearing because you have the `allTime` and `showWeekend` parameters set to false. Check out the README to see what they are used for, but if you'd like the module to show all the time then you can simply remove those two parameters from your config and it should work.
