### ISSUE TITLE
Conflict with classes attribute - double use with different values

### ISSUE THREAD

**Issue by ChrizZz90** [SamLewis0602/MMM-Traffic#76]
Hi,

currently I'm setting up the facial recognition tool where classes are used to show different modules for recognized persons or groups. This is very common for several modules but your module uses classes as a design value. Having both running there is a conflict between the classes for groups and your design solution. I can't handle classes for groups/person and as a design value together.

Is it possible to rename your "classes" attribute?

**Comment by SamLewis0602** [comment]
`classes` is technically not an attribute of MMM-Traffic, it is part of the magicmirror framework, that's why it's outside the `config` object in the example in the readme. I wrote this module 3 years ago, so it's possible the structure for MagicMirror itself has changed, I'm not sure. Please verify that if you can.

**Comment by SamLewis0602** [comment]
Ah, I think I understand. You're asking that the general MagicMirror classes attribute not be used within the module.

Let me take a look.

**Comment by SamLewis0602** [comment]
This is the only code in the module that references `this.data.classes` so I'm not sure how this would affect your use of it. Can you give me more info on what you're seeing?

```

**Comment by ChrizZz90** [comment]
I removed it and for me it's working now. But maybe the css colours changed a bit, I'm not really sure
