### ISSUE TITLE
Journey Time Validation

### ISSUE THREAD

**Issue by BillyTheKid9588** [SamLewis0602/MMM-Traffic#92]
Is it possible to validate the journey which is being used and how the time is being calculated?

I have tripled checked the coordinates i am using, and made sure that longitude and latitude are the correct way round.

Mapbox is giving me a journey time of 90 minutes whereas google maps is giving a journey time of 81 minutes. I also checked apple maps and it is giving me 79 minutes.

Thanks,

**Comment by SamLewis0602** [comment]
Hey there, you can use the Mapbox API's playgrounds feature. Make sure you're logged in to your account and it will automatically put your default API key in there for you. Make sure to choose "traffic" instead of driving to match the profile that MMM-Traffic uses.

https://docs.mapbox.com/playground/directions/
